### ISSUE TITLE
Issue unhiding link_to's based on current user and game.user_id

### ISSUE THREAD

**Issue by Ishmaru** [Ishmaru/indie_think_tank#1]
# Issue with line 9-13 of app/views/games/show.index.erb

``` Ruby
<% if current_user == @game.user_id %>
  <%= link_to "Update Game", edit_game_path(@game) %>
  <br>
  <%= link_to "Remove Game", game_path, method: :delete, data: {confirm: "Remove Game?"} %>
<% end %>
```
#### Explanation:

No syntax errors shown, however not functioning properly. The idea is to only show these links to the user who has the same id as the game.user_id. However, they remain hidden for all users including the owner.
#### To Test:

Make sure db is seeded, log in as "Ishmaru" password "1234" and navigate to Annex Conquer in root page (click name).  Ishmaru is the owner (It shows under Ishmaru's profile page) and links should appear under "Download" link.  If you need to navigate to profile page once you log in a link will appear in navbar.

**Comment by ezRAez** [comment]
Are they not showing?

**Comment by ezRAez** [comment]
I assume they are not because you're comparing an object (current_user) to an integer (game.user_id).

**Comment by Ishmaru** [comment]
can I use a .to_int would that work?

**Comment by Ishmaru** [comment]
@current_user does not work either, and @current_user was set to session[:user_id] in application controller.

**Comment by Ishmaru** [comment]
If I use session[:user_id], it does work. However, if @current_user is set to session[:user_id] i don't understand the difference. I would like to know why if anyone has a chance.

**Comment by ghost** [comment]
@ishmaru I'll sit with you in the AM if you need further guidance. Essentially current_user should not equal the user ID (an integer), it should equal _the user with that user ID._ Just like I am not "Phil," I am the person with the name "Phil." These ideas can be confusing.

**Comment by Ishmaru** [comment]
Ok that makes sense thank you!
